services:
  backend:
    image: backend:latest
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}